### ISSUE TITLE
Atlantis

### ISSUE THREAD

**Issue by UtpalJayNadiger** [raxod502/intuitive-explanations#26]
Hey Radon - Hope you don't mind me filing an issue for this. Basically, I stumbled upon this issue from 2020 (https://github.com/runatlantis/helm-charts/issues/14) and wanted to reach out to you to chat about what your current terraform automation setup looks like with Atlantis.

The reason I am interested is because we are building a more secure alternative (https://github.com/diggerhq/digger) and would love your thoughts/feedback on it!

Any chance you'd be open for a chat?

**Comment by raxod502** [comment]
I'll mention Digger to the team and reach out if we decide it's something we're looking to explore, thanks!
